api:
  host: localhost
  port: 8000
  timeout: 60
  
login:
  email: autopilote@example.com
  username: alphb
  password: mypassword

ship:
  name: ship-very-drunk2

logger:
  verbose: FALSE

ship_driving:
  choice: "autopilot"

kafka:
  host: localhost
  port: 9092